"""add_seller_id_to_templates

Revision ID: 0ef08c88630e
Revises: 903ee38ce36c
Create Date: 2026-07-02 19:20:40.746786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef08c88630e'
down_revision: Union[str, None] = '903ee38ce36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('seller_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_templates_seller_id'), 'templates', ['seller_id'], unique=False)
    op.create_foreign_key(None, 'templates', 'users', ['seller_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_index(op.f('ix_templates_seller_id'), table_name='templates')
    op.drop_column('templates', 'seller_id')
    # ### end Alembic commands ###
