"""Add oauth support

Revision ID: 903ee38ce36c
Revises: None
Create Date: 2026-06-30 02:21:17.611592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903ee38ce36c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('facebook_id', sa.String(length=255), nullable=True))
    op.drop_index('ix_users_clerk_id', table_name='users')
    op.create_index(op.f('ix_users_facebook_id'), 'users', ['facebook_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_facebook_id'), table_name='users')
    op.create_index('ix_users_clerk_id', 'users', ['clerk_id'], unique=True)
    op.drop_column('users', 'facebook_id')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
